steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-cxe'
  - |
        IMAGE=$$(echo $TAG_NAME | awk -F "-" '{print $1}')
        VERSION=$$(echo $TAG_NAME | awk -F "-" '{print $$NF}')
        cd $$IMAGE
        docker build -t gcr.io/$PROJECT_ID/$$IMAGE:$$VERSION .
        docker push gcr.io/$PROJECT_ID/$$IMAGE:$$VERSION
