steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
        TAG=
        docker build -t gcr.io/$PROJECT_ID/vegeta:$TAG .
        gcloud docker -- push gcr.io/$PROJECT_ID/vegeta:$TAG
